In [ ]:
import numpy as np

In [ ]:
# Q1 a
arr1=np.array([1,2,3,6,4,5])
# two methods
q1_a_1 = arr1[::-1]
q1_a_2 = np.flip(arr1)
print(q1_a_1)
print(q1_a_2)

[5 4 6 3 2 1]
[5 4 6 3 2 1]


In [ ]:
# Q1 b
arr2 = np.array([[1,2,3],[2,4,5],[1,2,3]])
q1_b = arr2.flatten()
print(q1_b)
arr3 = np.array([[1,2,3],[2,4,5],[1,2,3]])
q1_b_2 = arr3.ravel()
print(q1_b_2)
print(arr3)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]
[[1 2 3]
 [2 4 5]
 [1 2 3]]


In [ ]:
# Q1 c
arr4 = np.array([[1, 2], [3, 4]])
arr5 = np.array([[1, 2], [3, 4]])

is_equal = np.array_equal(arr4, arr5)
print(is_equal)

True


In [ ]:
# Q1 d
# i
arr6 = np.array([1,2,3,4,5,1,2,1,1,1])
maxele1 = np.bincount(arr6).argmax()
print(maxele1)
indices = np.where(arr6 == maxele1)
print(indices[0])

# ii
arr7 = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
y = np.bincount(arr7)
maximum = max(y)

most_frequent = []
for i in range(len(y)):
    if y[i] == maximum:
        print(i, end=" ")
        most_frequent.append(i)
print("\n")

for value in most_frequent:
    print(f"indices of {value}: {np.where(arr7 == value)[0]}")

1
[0 5 7 8 9]
1 3 

indices of 1: [0 1 2]
indices of 3: [4 8 9]


In [ ]:
# Q1 e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg)
sum = np.sum(gfg)
print(sum)
print(np.sum(gfg, axis=0))
print(np.sum(gfg, axis=1))

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
45
[[20  9 16]]
[[14]
 [16]
 [15]]


In [ ]:
# Q1 f
# i
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
trace = np.trace(n_array)
print(trace)
# ii
eigenvalues, eigenvectors = np.linalg.eig(gfg)
print("Eigenvalues:", eigenvalues)
# iii
print("Eigenvectors:", eigenvectors)
# iv
print("Inverse:", np.linalg.inv(gfg))
# v
print("Determinant:", np.linalg.det(gfg))


176
Eigenvalues: [14.82527413+0.j        -0.91263707+5.2179769j -0.91263707-5.2179769j]
Eigenvectors: [[-0.54315313+0.j         -0.24714905+0.37800988j -0.24714905-0.37800988j]
 [-0.60078042+0.j          0.80232082+0.j          0.80232082-0.j        ]
 [-0.58655568+0.j         -0.17340156-0.34962704j -0.17340156+0.34962704j]]
Inverse: [[ 0.03125     0.09375    -0.0625    ]
 [-0.16346154 -0.02884615  0.25      ]
 [ 0.11538462 -0.03846154  0.        ]]
Determinant: 416.0


In [ ]:
# Q1 g

p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print(np.dot(p, q))
print(np.cov(p.flatten(), q.flatten()))

p1 = np.array([[1, 2], [2, 3], [4, 5]])
q1 = np.array([[4, 5, 1], [6, 7, 2]])
print(np.dot(p1, q1))
print(np.cov(p1.flatten(), q1.flatten()))

[[16 19]
 [26 31]]
[[0.66666667 1.        ]
 [1.         1.66666667]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
# Q1 h

x1 = np.array([[2, 3, 4], [3, 2, 9]])
y1 = np.array([[1, 5, 0], [5, 10, 3]])

print(np.inner(x1, y1))
print(np.outer(x1, y1))
print(np.cross(x1, y1))


[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[-20   4   7]
 [-84  36  20]]


In [ ]:
# Q2 a
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(np.abs(array))

percentiles_flat = np.percentile(array, [25, 50, 75])
print(percentiles_flat)
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
print(percentiles_columns)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=0)
print(percentiles_rows)

[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]


In [ ]:
# Q2 iii
# Flattened statistics
mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)
print(f"\nFlattened array - Mean: {mean_flat}, Median: {median_flat}, Std Dev: {std_flat}")

# Column-wise statistics (axis=0)
mean_cols = np.mean(array, axis=0)
median_cols = np.median(array, axis=0)
std_cols = np.std(array, axis=0)
print(mean_cols)
print(median_cols)
print(std_cols)

# Row-wise statistics (axis=1)
mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)
print(mean_rows)
print(median_rows)
print(std_rows)


Flattened array - Mean: -0.5, Median: -0.5, Std Dev: 3.8622100754188224
[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]
[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]


In [ ]:
# Q2 b
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
array2 = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array2))
indices_sorted = np.argsort(array2)
print(indices_sorted)
four_smallest = np.sort(array2)[:4]
print(four_smallest)
fifth_largest = np.sort(array2)[-5:]
print(fifth_largest)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [ ]:
# Q3 b
array3 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print(array3[array3 == np.floor(array3)])
print(array3[array3 != np.floor(array3)])


[1. 2. 3. 2.]
[1.2 2.2]


In [ ]:
# Q 4
from PIL import Image
import os

def img_to_array(path):
    with Image.open(path) as img:
        base = os.path.splitext(os.path.basename(path))[0]
        if img.mode == 'L':
            arr = np.array(img)
            filename = base + '_gray.txt'
            np.savetxt(filename, arr, fmt='%d')
            print(f"Grayscale image array saved as {filename}")
        else:
            img = img.convert('RGB')
            arr = np.array(img)
            arr_2d = arr.reshape(-1, arr.shape[-1])
            filename = base + '_rgb.txt'
            np.savetxt(filename, arr_2d, fmt='%d')
            print(f"RGB image array saved as {filename}")

print(os.path.exists(r'C:\grayscale.JPG'))
print(os.getcwd())





False
/content


In [ ]:
from google.colab import files
uploaded = files.upload()


Saving grayscale.jpg to grayscale.jpg


In [ ]:
from PIL import Image
import os

def img_to_array(path):
    with Image.open(path) as img:
        base = os.path.splitext(os.path.basename(path))[0]
        if img.mode == 'L':  
            arr = np.array(img)
            filename = base + '_gray.txt'
            np.savetxt(filename, arr, fmt='%d')
            print(f"Grayscale image array saved as {filename}")
        elif img.mode in ['RGB', 'RGBA']:
            img = img.convert('RGB')
            arr = np.array(img)
            arr_2d = arr.reshape(-1, arr.shape[-1])
            filename = base + '_rgb.txt'
            np.savetxt(filename, arr_2d, fmt='%d')
            print(f"RGB image array saved as {filename}")
        else:
            print("Unsupported image mode:", img.mode)

img_to_array('grayscale.jpg')


RGB image array saved as grayscale_rgb.txt


In [ ]:
arr = np.loadtxt('grayscale_rgb.txt', dtype=int)
print(arr.shape)         
print(arr)              

import matplotlib.pyplot as plt
plt.imshow(arr, cmap='gray')
plt.axis('off')
plt.show()

(24000000, 3)
[[217 217 217]
 [217 217 217]
 [217 217 217]
 ...
 [ 23  23  23]
 [ 22  22  22]
 [ 19  19  19]]


/usr/local/lib/python3.11/dist-packages/matplotlib/image.py:183: UserWarning: Data with more than 2**24 rows cannot be accurately displayed. Downsampling to less than 2**24 rows before displaying. To remove this warning, manually downsample your data.
  warnings.warn(msg.format(n='2**24 rows'))
